### ISSUE TITLE
check for 'root' or 'vagrant' in email address

### ISSUE THREAD

**Issue by beav** [theforeman/prprocessor#107]
It's easy to mistakenly create a commit as 'root' or 'vagrant' user, and difficult to spot this error when doing PR review. It would be good if the prprocessor checked for this.

I don't have a dev environment for prprocessor, but I believe something like this untested patch should do it:

```diff
diff --git a/github/pull_request.rb b/github/pull_request.rb
index 980938a..31c221f 100644
--- a/github/pull_request.rb
+++ b/github/pull_request.rb
@@ -98,6 +98,10 @@ class PullRequest
         warnings += "  * #{commit.sha} must be in the format ```fixes #redmine_number - brief description```\n"
         short_warnings[commit.sha] << 'issue number format'
       end
+      if commit.commit.committer.email =~ /\A(vagrant@|root@)/
+        warnings += "  * #{commit.sha} must not be authored by vagrant or root user\n"
+        short_warnings[commit.sha] << 'vagrant or root in commit author email'
+      end
       if commit.commit.message.lines.first.chomp.size > 65
         warnings += "  * length of the first commit message line for #{commit.sha} exceeds 65 characters\n"
         short_warnings[commit.sha] << 'summary line length exceeded'
```

**Comment by beav** [comment]
@ekohl this is the issue related to our IRC discussion. I'm not able to easily test it, do you already have a test env for prprocessor?

**Comment by ekohl** [comment]
@beav I don't. It'd be easier if you submitted this as a PR instead of an issue with a patch. I'd be happy to merge it, deploy and see if it work since this looks fairly straight forward and a revert is quick.
