### ISSUE TITLE
auto set repo labels based on file paths

### ISSUE THREAD

**Issue by ohadlevy** [theforeman/prprocessor#114]
as a developer, I would like to auto add certain labels based on file changed.

for example, anything under /webpack should get a UI label, maybe any file changing css files should have a UX flag.

**Comment by ekohl** [comment]
For community-templates we have code already. It is limited to top level paths only but configuration is [here](https://github.com/theforeman/prprocessor/blob/7f220b0cb4c19767857790387d9eefc32ffa95d5/config/repos.yaml#L12-L17). That should already cover the `webpack` directory and should be trivial to implement.

There is an annoying bug that it sometimes sets the label even if it's already applied but it doesn't generate an email so hasn't had priority to fix it.

**Comment by ohadlevy** [comment]
meaning we can just use this feature now? is it published some where? if
not, would you mind sending that to the forum so folks can start adding
labels as needed?

**Comment by ekohl** [comment]
Yes, a PR to `repos.yaml` should suffice. The PR processor is a bit underdocumented in general.

**Comment by ekohl** [comment]
This as implemented in 2eb242f02078357a9bfac713a5ccb457e1ef4322 but dropped just now in e7a777afe810d1850ef2049efce6b7a36b59a4eb to be replaced with https://github.com/actions/labeler
