### ISSUE TITLE
How to add repositories to REDMINE_ISSUE_REQUIRED_REPOS list

### ISSUE THREAD

**Issue by ehelms** [theforeman/prprocessor#26]
Since this is an environment variable that must be set, I wasn't sure how to add or request for repositories to be included (as well I didn't see this information on the plugin wiki pages). Should I just request access here? or the mailing list? Or convert this to a configuration file such that PRs can be opened to add repositories?

**Comment by domcleal** [comment]
Yeah, any of those!
