### ISSUE TITLE
Inactivitiy reminder after X days

### ISSUE THREAD

**Issue by stbenjam** [theforeman/prprocessor#32]
Would it be possible to comment after X days of inactivity?

Sometimes I'll review a PR, they'll fix some stuff, but I'll forget to come back to it.

**Comment by ehelms** [comment]
It would have to grab all PRs for all repositories and analyze them which I believe is something the PR scanner is doing already so perhaps thats the place to do this. This could be the vehicle for commenting (but triggered by the PR scanner's results).

**Comment by GregSutcliffe** [comment]
Slight hijack, but might be relevant to bring up on [this discussion](https://groups.google.com/forum/#!topic/foreman-dev/jiOx3_WeGmg) - whatever I can use/adapt for those proposals will mean I don't have to build something new.

**Comment by stbenjam** [comment]
I think this was more or less resolved by https://github.com/theforeman/prprocessor/issues/32
