### ISSUE TITLE
Work with multiple pull requests per issue

### ISSUE THREAD

**Issue by domcleal** [theforeman/prprocessor#4]
The PR field in a redmine ticket can only store a single PR, so using the same ticket number to fix an issue in multiple repos may cause it to cycle between states (especially when PRs get updated).

Perhaps the field shouldn't be set if it already has a value, or perhaps check if the existing PR is open or not before updating it.

Ideally we need to keep a list of all PRs though, so perhaps the custom field can be changed to another format (are multiple entries possible?) or additional PRs could be added as comments.

**Comment by ehelms** [comment]
See https://github.com/theforeman/redmine/pull/13 for a first crack at this from the Redmine side. Updating this repo to use that patch will be trivial.

**Comment by domcleal** [comment]
Fixed via #30/
